version: "2"
linters:
  enable:
    - errorlint
    - gosec
    - revive
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/rootwarp/eth-call
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
